#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/utils.js:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/utils.js
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/xdc.tci:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/xdc.tci
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/template.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/template.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/om2.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/om2.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen2.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen2.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/Warnings.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/Warnings.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/IPackage.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/IPackage.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/package.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/package.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Clock.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Clock.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Trace.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Trace.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/bld.js:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/bld.js
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/BuildEnvironment.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/PackageContents.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/PackageContents.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/_gen.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/_gen.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Library.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Library.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Executable.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Executable.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Repository.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Repository.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Configuration.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Configuration.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Script.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Script.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Manifest.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Manifest.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Utils.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Utils.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget2.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget2.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget3.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget3.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITargetFilter.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/package.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/package.xs
package.mak: config.bld
Z:/ti/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/ITarget.xs:
package.mak: Z:/ti/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/ITarget.xs
Z:/ti/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/package.xs:
package.mak: Z:/ti/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/package.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/File.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/File.xs
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/package.xs:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/package.xs
package.mak: package.bld
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: Z:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

iar.targets.arm.M3.rootDir ?= C:/PROGRA~2/IARSYS~1/EMBEDD~1.2/arm
iar.targets.arm.packageBase ?= Z:/ti/tirtos_simplelink_2_11_01_09/products/bios_6_41_02_41/packages/iar/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.orm3
.PHONY: all,rm3 .dlls,rm3 .executables,rm3 test,rm3
all,rm3: .executables,rm3
.executables,rm3: .libraries,rm3
.executables,rm3: .dlls,rm3
.dlls,rm3: .libraries,rm3
.libraries,rm3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm3
	@$(ECHO) xdc .executables,rm3
	@$(ECHO) xdc .libraries,rm3
	@$(ECHO) xdc .dlls,rm3


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,rm3 .dlls: app.prm3

-include package/cfg/app_prm3.mak
-include package/cfg/app_prm3.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/app_prm3.dep
endif
app.prm3: package/cfg/app_prm3.xdl
	@


ifeq (,$(wildcard .libraries,rm3))
app.prm3 package/cfg/app_prm3.c: .libraries,rm3
endif

package/cfg/app_prm3.c package/cfg/app_prm3.h package/cfg/app_prm3.xdl: override _PROG_NAME := app.xrm3
package/cfg/app_prm3.c: package/cfg/app_prm3.cfg
package/cfg/app_prm3.xdc.inc: package/cfg/app_prm3.xdl
package/cfg/app_prm3.xdl package/cfg/app_prm3.c: .interfaces

clean:: clean,rm3
	-$(RM) package/cfg/app_prm3.cfg
	-$(RM) package/cfg/app_prm3.dep
	-$(RM) package/cfg/app_prm3.c
	-$(RM) package/cfg/app_prm3.xdc.inc

clean,rm3::
	-$(RM) app.prm3
.executables,rm3 .executables: app.xrm3

app.xrm3: |app.prm3

-include package/cfg/app.xrm3.mak
app.xrm3: package/cfg/app_prm3.orm3 
	$(RM) $@
	@$(MSG) lnkrm3 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	LC_ALL=C $(iar.targets.arm.M3.rootDir)/bin/ilinkarm -o Z:/ti/simplelink/zstack_home_1_02_02a_44539/Projects/zstack/HomeAutomation/WeatherStation/CC2650/SensorTag/Exe/SensorTag.out --config_def CC2650=1 --config_def USE_SYSBIOS_IN_ROM=1 --map Z:/ti/simplelink/zstack_home_1_02_02a_44539/Projects/zstack/HomeAutomation/WeatherStation/CC2650/SensorTag/List/SensorTag.map --config Z:/ti/simplelink/zstack_home_1_02_02a_44539/Projects/zstack/HomeAutomation/WeatherStation/CC2650/cc26xx_app.icf --keep __vector_table -f Z:/ti/simplelink/zstack_home_1_02_02a_44539/Projects/zstack/HomeAutomation/WeatherStation/CC2650/configPkg/linker.cmd -f Z:/ti/simplelink/zstack_home_1_02_02a_44539/Projects/zstack/HomeAutomation/WeatherStation/CC2650/../../../Core/Thread/CC26xx/Config/coreEndDevice.xcl --semihosting Z:/ti/tirtos_simplelink_2_11_01_09/products/cc26xxware_2_00_06_14829/driverlib/bin/iar/driverlib.lib Z:/ti/simplelink/zstack_home_1_02_02a_44539/Projects/zstack/HomeAutomation/WeatherStation/CC2650/../../../../../Projects/common/TIMAC_ROM_Release/03282014/timac_rom_PATCH.symbols --entry __iar_program_start --inline --vfe --silent -o $@ package/cfg/app_prm3.orm3 -f package/cfg/app_prm3.xdl  --semihosting=iar_breakpoint  --cpu=Cortex-M3 --map $(XDCCFGDIR)/$@.map  --redirect _Printf=_PrintfSmall --redirect _Scanf=_ScanfSmall 
	

app.test test,rm3 test: app.xrm3.test

app.xrm3.test:: app.xrm3
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 app.xrm3.test
else
	@$(MSG) running $<  ...
	$(call EXEC.app.xrm3, ) 
endif

clean,rm3::
	-$(RM) $(wildcard .tmp,app.xrm3,*)


clean:: clean,rm3

clean,rm3::
	-$(RM) app.xrm3
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
app_prm3.orm3,copy : package/cfg/app_prm3.orm3
app_prm3.srm3,copy : package/cfg/app_prm3.srm3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.bld.xml
package/rel/configPkg/configPkg/package/package.rel.xml: package/build.cfg
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.xdc.inc
package/rel/configPkg/configPkg/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
